{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDefaultConfigIfNeeded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdkconfigurations\/configurations\/adddefaultconfigifneeded(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdkconfigurations\/configurations\/adddefaultconfigifneeded(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/addDefaultConfigIfNeeded(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a default type of Configuration for the Type passed in and"},{"type":"text","text":" "},{"type":"text","text":"adds it to the internal array"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"addDefaultConfigIfNeeded:"}],"role":"symbol","title":"addDefaultConfigIfNeeded(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDefaultConfigIfNeeded"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@SDKConfigurations@objc(cs)ZDKConfigurations(im)addDefaultConfigIfNeeded:","modules":[{"name":"SDKConfigurations"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations"]]},"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"role":"symbol","title":"Configurations","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurations"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurations"}],"url":"\/documentation\/sdkconfigurations\/configurations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configuration":{"role":"symbol","title":"Configuration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/sdkconfigurations\/configuration"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/addDefaultConfigIfNeeded(_:)":{"role":"symbol","title":"addDefaultConfigIfNeeded(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDefaultConfigIfNeeded"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a default type of Configuration for the Type passed in and"},{"type":"text","text":" "},{"type":"text","text":"adds it to the internal array"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/addDefaultConfigIfNeeded(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addDefaultConfigIfNeeded:"}],"url":"\/documentation\/sdkconfigurations\/configurations\/adddefaultconfigifneeded(_:)"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"role":"collection","title":"SDKConfigurations","abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addDefaultConfigIfNeeded:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDefaultConfigIfNeeded:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addDefaultConfigIfNeeded:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ZDKConfiguration>","preciseIdentifier":"c:Qo@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title","value":"ZDKConfigurations"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments","value":[{"kind":"identifier","text":"ZDKConfigurations"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/title","value":"ZDKConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/fragments","value":[{"kind":"identifier","text":"ZDKConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1addDefaultConfigIfNeeded(_:)\/title","value":"addDefaultConfigIfNeeded:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1addDefaultConfigIfNeeded(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDefaultConfigIfNeeded:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}