{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDefaultConfigIfNeeded"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"ofType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC24addDefaultConfigIfNeeded6ofTypeyxm_tAA13ConfigurationRzlF1TL_xmfp"},{"kind":"text","text":".Type) "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type that we want a default config created for."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdkconfigurations\/configurations\/adddefaultconfigifneeded(oftype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/addDefaultConfigIfNeeded(ofType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a default type of Configuration for the Type passed in and"},{"type":"text","text":" "},{"type":"text","text":"adds it to the internal array"}],"kind":"symbol","metadata":{"role":"symbol","title":"addDefaultConfigIfNeeded(ofType:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDefaultConfigIfNeeded"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"ofType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC24addDefaultConfigIfNeeded6ofTypeyxm_tAA13ConfigurationRzlF1TL_xmfp"},{"kind":"text","text":".Type)"}],"symbolKind":"method","externalID":"s:17SDKConfigurations14ConfigurationsC24addDefaultConfigIfNeeded6ofTypeyxm_tAA13ConfigurationRzlF","extendedModule":"SDKConfigurations","modules":[{"name":"SDKConfigurations"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations"]]},"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/addDefaultConfigIfNeeded(ofType:)":{"role":"symbol","title":"addDefaultConfigIfNeeded(ofType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDefaultConfigIfNeeded"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"ofType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC24addDefaultConfigIfNeeded6ofTypeyxm_tAA13ConfigurationRzlF1TL_xmfp"},{"kind":"text","text":".Type)"}],"abstract":[{"type":"text","text":"Creates a default type of Configuration for the Type passed in and"},{"type":"text","text":" "},{"type":"text","text":"adds it to the internal array"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/addDefaultConfigIfNeeded(ofType:)","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations\/adddefaultconfigifneeded(oftype:)"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"role":"collection","title":"SDKConfigurations","abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configuration":{"role":"symbol","title":"Configuration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/sdkconfigurations\/configuration"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"role":"symbol","title":"Configurations","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurations"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurations"}],"url":"\/documentation\/sdkconfigurations\/configurations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/title","value":"ZDKConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/fragments","value":[{"kind":"identifier","text":"ZDKConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title","value":"ZDKConfigurations"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments","value":[{"kind":"identifier","text":"ZDKConfigurations"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}