{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations"},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/objc(pl)NSObject","doc:\/\/com.zendesk.SDKConfigurations\/s7CVarArgP","doc:\/\/com.zendesk.SDKConfigurations\/Sl","doc:\/\/com.zendesk.SDKConfigurations\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SDKConfigurations\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SDKConfigurations\/SQ","doc:\/\/com.zendesk.SDKConfigurations\/s25ExpressibleByArrayLiteralP","doc:\/\/com.zendesk.SDKConfigurations\/SH","doc:\/\/com.zendesk.SDKConfigurations\/ST"],"title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdkconfigurations\/configurations"]},{"paths":["\/documentation\/sdkconfigurations\/configurations"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@SDKConfigurations@objc(cs)ZDKConfigurations","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configurations","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"text":"Configurations","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"SDKConfigurations"}],"title":"Configurations"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/init(configs:)"]},{"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/configs"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/addDefaultConfigIfNeeded(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/addDefaultConfigIfNeeded(ofType:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/insert(_:)"]},{"title":"Subscripts","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/subscript(forType:)"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/ConfigArrayType"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Collection-Implementations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/ExpressibleByArrayLiteral-Implementations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Sequence-Implementations"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKConfigurations) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configurations","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.zendesk.SDKConfigurations/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/objc(cs)NSObject"},"doc://com.zendesk.SDKConfigurations/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/addDefaultConfigIfNeeded(_:)":{"title":"addDefaultConfigIfNeeded(_:)","role":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/addDefaultConfigIfNeeded(_:)","type":"topic","abstract":[{"text":"Creates a default type of Configuration for the Type passed in and","type":"text"},{"type":"text","text":" "},{"type":"text","text":"adds it to the internal array"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDefaultConfigIfNeeded"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/sdkconfigurations\/configurations\/adddefaultconfigifneeded(_:)","navigatorTitle":[{"kind":"identifier","text":"addDefaultConfigIfNeeded:"}]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ZDKConfigurations/objectAtIndexedSubscript:":{"title":"objectAtIndexedSubscript:","url":"\/documentation\/sdkconfigurations\/zdkconfigurations\/objectatindexedsubscript:","role":"symbol","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"objectAtIndexedSubscript:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ZDKConfigurations\/objectAtIndexedSubscript:","fragments":[{"kind":"text","text":"- "},{"text":"objectAtIndexedSubscript:","kind":"identifier"}]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/insert(_:)":{"type":"topic","title":"insert(_:)","navigatorTitle":[{"text":"insert:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"insert","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/insert(_:)","url":"\/documentation\/sdkconfigurations\/configurations\/insert(_:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Inserts a "},{"code":"Configuration","type":"codeVoice"},{"type":"text","text":" object into the array"}]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"type":"topic","kind":"symbol","title":"SDKConfigurations","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","url":"\/documentation\/sdkconfigurations","role":"collection","abstract":[]},"doc://com.zendesk.SDKConfigurations/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SDKConfigurations/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/Sequence-Implementations":{"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Sequence-Implementations","abstract":[],"title":"Sequence Implementations","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations\/sequence-implementations","role":"collectionGroup","kind":"article"},"doc://com.zendesk.SDKConfigurations/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/addDefaultConfigIfNeeded(ofType:)":{"type":"topic","title":"addDefaultConfigIfNeeded(ofType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addDefaultConfigIfNeeded","kind":"identifier"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"text":"ofType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC24addDefaultConfigIfNeeded6ofTypeyxm_tAA13ConfigurationRzlF1TL_xmfp"},{"kind":"text","text":".Type)"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/addDefaultConfigIfNeeded(ofType:)","url":"\/documentation\/sdkconfigurations\/configurations\/adddefaultconfigifneeded(oftype:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Creates a default type of Configuration for the Type passed in and"},{"text":" ","type":"text"},{"type":"text","text":"adds it to the internal array"}]},"doc://com.zendesk.SDKConfigurations/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SDKConfigurations/Sl":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/Sl","title":"Swift.Collection"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/ConfigArrayType":{"kind":"symbol","title":"Configurations.ConfigArrayType","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConfigArrayType"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/ConfigArrayType","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConfigArrayType"}],"type":"topic","url":"\/documentation\/sdkconfigurations\/configurations\/configarraytype"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/ExpressibleByArrayLiteral-Implementations":{"title":"ExpressibleByArrayLiteral Implementations","url":"\/documentation\/sdkconfigurations\/configurations\/expressiblebyarrayliteral-implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/ExpressibleByArrayLiteral-Implementations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"title":"Configurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configurations","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","navigatorTitle":[{"kind":"identifier","text":"Configurations"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/Collection-Implementations":{"title":"Collection Implementations","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Collection-Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations\/collection-implementations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/configs":{"title":"configs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configs"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"configs","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConfigArrayType","kind":"typeIdentifier","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC15ConfigArrayTypea"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/configs","url":"\/documentation\/sdkconfigurations\/configurations\/configs","role":"symbol","kind":"symbol","abstract":[]},"doc://com.zendesk.SDKConfigurations/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/s25ExpressibleByArrayLiteralP","title":"Swift.ExpressibleByArrayLiteral","type":"unresolvable"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/init(configs:)":{"title":"init(configs:)","abstract":[{"type":"text","text":"Initializes a new SDKConfiguration object."}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfigs:"}],"url":"\/documentation\/sdkconfigurations\/configurations\/init(configs:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"text":"])","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/init(configs:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/subscript(forType:)":{"title":"subscript(forType:)","type":"topic","fragments":[{"text":"subscript","kind":"keyword"},{"kind":"text","text":"<"},{"text":"T","kind":"genericParameter"},{"kind":"text","text":">("},{"kind":"externalParam","text":"forType"},{"text":" _: ","kind":"text"},{"text":"T","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC7forTypexSgxm_tcAA13ConfigurationRzluip1TL_xmfp","kind":"typeIdentifier"},{"text":".Type) -> ","kind":"text"},{"preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC7forTypexSgxm_tcAA13ConfigurationRzluip1TL_xmfp","text":"T","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/subscript(forType:)","url":"\/documentation\/sdkconfigurations\/configurations\/subscript(fortype:)","role":"symbol","kind":"symbol","abstract":[{"text":"Returns the first ","type":"text"},{"code":"Configuration","type":"codeVoice"},{"type":"text","text":" object that is of "},{"code":"T","type":"codeVoice"}]},"doc://com.zendesk.SDKConfigurations/ST":{"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/ST","title":"Swift.Sequence","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKConfigurations","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKConfigurations"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConfigurations"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/configs"]},{"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/addDefaultConfigIfNeeded(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/init(configs:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/insert(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ZDKConfigurations\/objectAtIndexedSubscript:"],"title":"Instance Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Collection-Implementations"],"generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/objc(cs)NSObject"],"kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConfigurations","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1addDefaultConfigIfNeeded(_:)\/title","op":"replace","value":"addDefaultConfigIfNeeded:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1addDefaultConfigIfNeeded(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addDefaultConfigIfNeeded:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1insert(_:)\/title","value":"insert:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1insert(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"insert:","kind":"identifier"}]},{"value":"ZDKConfigurations","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments","value":[{"text":"ZDKConfigurations","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1configs\/title","op":"replace","value":"configs"},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1configs\/fragments","op":"replace","value":[{"kind":"identifier","text":"configs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1init(configs:)\/title","value":"initWithConfigs:"},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1init(configs:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithConfigs:","kind":"identifier"}]}]}]}