{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations"]]},"identifier":{"url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration\/init()"]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/objc(pl)NSObject"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKConfiguration) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"symbolKind":"protocol","role":"symbol","externalID":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"SDKConfigurations"}]},"variants":[{"paths":["\/documentation\/sdkconfigurations\/configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdkconfigurations\/configuration"]}],"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configuration":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"Configuration","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration","url":"\/documentation\/sdkconfigurations\/configuration","role":"symbol","abstract":[]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configuration/init()":{"title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdkconfigurations\/configuration\/init()","type":"topic","required":true,"role":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration\/init()","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.zendesk.SDKConfigurations/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"type":"topic","kind":"symbol","title":"SDKConfigurations","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","url":"\/documentation\/sdkconfigurations","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"ZDKConfiguration"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ZDKConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration\/init()"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/objc(pl)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConfiguration","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"ZDKConfiguration","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/fragments","value":[{"text":"ZDKConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration~1init()\/title","value":"init","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}