{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurationError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdkconfigurations\/configurationerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdkconfigurations\/configurationerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/10Foundation14LocalizedErrorP","doc:\/\/com.zendesk.SDKConfigurations\/SQ","doc:\/\/com.zendesk.SDKConfigurations\/s5ErrorP","doc:\/\/com.zendesk.SDKConfigurations\/SH","doc:\/\/com.zendesk.SDKConfigurations\/SY","doc:\/\/com.zendesk.SDKConfigurations\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enum for Configuration error"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurationError"}],"title":"ConfigurationError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SDKConfigurations@E@ConfigurationError","modules":[{"name":"SDKConfigurations"}],"navigatorTitle":[{"kind":"identifier","text":"ConfigurationError"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/noConfig"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/Equatable-Implementations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/Error-Implementations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/LocalizedError-Implementations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdkconfigurations\/configurationerror\/localizederror-implementations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations\/configurationerror\/init(rawvalue:)"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"role":"collection","title":"SDKConfigurations","abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations"},"doc://com.zendesk.SDKConfigurations/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/s8SendableP"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationError":{"role":"symbol","title":"ConfigurationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurationError"}],"abstract":[{"type":"text","text":"Enum for Configuration error"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfigurationError"}],"url":"\/documentation\/sdkconfigurations\/configurationerror"},"doc://com.zendesk.SDKConfigurations/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/SY"},"doc://com.zendesk.SDKConfigurations/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/10Foundation14LocalizedErrorP"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationError/noConfig":{"role":"symbol","title":"ConfigurationError.noConfig","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noConfig"}],"abstract":[{"type":"text","text":"error case for no Configuration present"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/noConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfigurationErrorNoConfig"}],"url":"\/documentation\/sdkconfigurations\/configurationerror\/noconfig"},"doc://com.zendesk.SDKConfigurations/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/SQ"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdkconfigurations\/configurationerror\/rawrepresentable-implementations"},"doc://com.zendesk.SDKConfigurations/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/s5ErrorP"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdkconfigurations\/configurationerror\/equatable-implementations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdkconfigurations\/configurationerror\/error-implementations"},"doc://com.zendesk.SDKConfigurations/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ConfigurationError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConfigurationError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ConfigurationError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/noConfig"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurationError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1ConfigurationError\/title","value":"ConfigurationError"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1ConfigurationError\/fragments","value":[{"kind":"identifier","text":"ConfigurationError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1ConfigurationError~1noConfig\/title","value":"ConfigurationErrorNoConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1ConfigurationError~1noConfig\/fragments","value":[{"kind":"identifier","text":"ConfigurationErrorNoConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}