{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdkconfigurations\/configurationerror\/noconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdkconfigurations\/configurationerror\/noconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/noConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"error case for no Configuration present"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noConfig"}],"title":"ConfigurationError.noConfig","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SDKConfigurations@E@ConfigurationError@ConfigurationErrorNoConfig","modules":[{"name":"SDKConfigurations"}],"navigatorTitle":[{"kind":"identifier","text":"ConfigurationErrorNoConfig"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError"]]},"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationError":{"role":"symbol","title":"ConfigurationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigurationError"}],"abstract":[{"type":"text","text":"Enum for Configuration error"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfigurationError"}],"url":"\/documentation\/sdkconfigurations\/configurationerror"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"role":"collection","title":"SDKConfigurations","abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationError/noConfig":{"role":"symbol","title":"ConfigurationError.noConfig","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noConfig"}],"abstract":[{"type":"text","text":"error case for no Configuration present"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError\/noConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfigurationErrorNoConfig"}],"url":"\/documentation\/sdkconfigurations\/configurationerror\/noconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ConfigurationErrorNoConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConfigurationErrorNoConfig"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ConfigurationErrorNoConfig"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1ConfigurationError\/title","value":"ConfigurationError"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1ConfigurationError\/fragments","value":[{"kind":"identifier","text":"ConfigurationError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1ConfigurationError~1noConfig\/title","value":"ConfigurationErrorNoConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1ConfigurationError~1noConfig\/fragments","value":[{"kind":"identifier","text":"ConfigurationErrorNoConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}