{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration"]},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError"]}],"identifier":{"url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdkconfigurations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdkconfigurations"]}],"hierarchy":{"paths":[[]]},"metadata":{"modules":[{"name":"SDKConfigurations"}],"roleHeading":"Framework","title":"SDKConfigurations","role":"collection","externalID":"SDKConfigurations","symbolKind":"module"},"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"title":"SDKConfigurations","url":"\/documentation\/sdkconfigurations","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","role":"collection"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","title":"Configurations","role":"symbol","navigatorTitle":[{"text":"Configurations","kind":"identifier"}],"abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configurations"}],"type":"topic"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configuration":{"url":"\/documentation\/sdkconfigurations\/configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationErrorDomain":{"abstract":[],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationErrorDomain","role":"symbol","title":"ConfigurationErrorDomain","type":"topic","url":"\/documentation\/sdkconfigurations\/configurationerrordomain","fragments":[{"kind":"identifier","text":"ConfigurationErrorDomain"}],"kind":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/SDKConfigurationsVersionNumber":{"abstract":[{"text":"Project version number for SDKConfigurations.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/SDKConfigurationsVersionNumber","kind":"symbol","role":"symbol","title":"SDKConfigurationsVersionNumber","url":"\/documentation\/sdkconfigurations\/sdkconfigurationsversionnumber","type":"topic","fragments":[{"kind":"identifier","text":"SDKConfigurationsVersionNumber"}]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/ConfigurationError":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConfigurationError","kind":"identifier"}],"abstract":[{"text":"Enum for Configuration error","type":"text"}],"title":"ConfigurationError","navigatorTitle":[{"text":"ConfigurationError","kind":"identifier"}],"url":"\/documentation\/sdkconfigurations\/configurationerror","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/SDKConfigurationsVersionString":{"title":"SDKConfigurationsVersionString","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/SDKConfigurationsVersionString","role":"symbol","url":"\/documentation\/sdkconfigurations\/sdkconfigurationsversionstring","fragments":[{"kind":"identifier","text":"SDKConfigurationsVersionString"}],"abstract":[{"type":"text","text":"Project version string for SDKConfigurations."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations"]},{"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationErrorDomain","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/SDKConfigurationsVersionNumber","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/SDKConfigurationsVersionString"]},{"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/ConfigurationError"],"title":"Enumerations"}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"ZDKConfigurations","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKConfigurations"}],"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/title","value":"ZDKConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/fragments","value":[{"text":"ZDKConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1ConfigurationError\/title","value":"ConfigurationError"},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1ConfigurationError\/fragments","op":"replace","value":[{"text":"ConfigurationError","kind":"identifier"}]}]}]}