{"metadata":{"modules":[{"name":"SDKConfigurations"}],"role":"collectionGroup","title":"Collection Implementations"},"variants":[{"paths":["\/documentation\/sdkconfigurations\/configurations\/collection-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdkconfigurations\/configurations\/collection-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Collection-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations"]]},"kind":"article","topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/count","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/endIndex","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/first","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/indices","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/isEmpty","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/startIndex","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/underestimatedCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/distance(from:to:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/drop(while:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/dropFirst(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/dropLast(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/firstIndex(where:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/formIndex(_:offsetBy:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/formIndex(_:offsetBy:limitedBy:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/formIndex(after:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/index(_:offsetBy:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/index(_:offsetBy:limitedBy:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/index(after:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/makeIterator()","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/map(_:)-u8uh","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(through:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(upTo:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(while:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/randomElement()","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/randomElement(using:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/split(maxSplits:omittingEmptySubsequences:whereSeparator:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/suffix(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/suffix(from:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/trimmingPrefix(while:)"],"generated":true},{"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/subscript(_:)"],"generated":true,"title":"Subscripts"},{"title":"Type Aliases","generated":true,"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Index"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/startIndex":{"title":"startIndex","url":"\/documentation\/sdkconfigurations\/configurations\/startindex","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/startIndex","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"startIndex","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Index","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa"}],"navigatorTitle":[{"kind":"identifier","text":"startIndex"}],"abstract":[{"text":"The position of the first element in a nonempty array.","type":"text"}]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/distance(from:to:)":{"title":"distance(from:to:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/distance(from:to:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"text":"Index","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Index"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/distance(from:to:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/indices":{"title":"indices","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/indices","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indices"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SI","text":"DefaultIndices","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":">"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/indices","role":"symbol","conformance":{"constraints":[{"code":"Indices","type":"codeVoice"},{"type":"text","text":" is "},{"code":"DefaultIndices<Self>","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]}},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/isEmpty":{"title":"isEmpty","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/isempty","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isEmpty","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/isEmpty","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/prefix(through:)":{"title":"prefix(through:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/prefix(through:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefix"},{"kind":"text","text":"("},{"text":"through","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Index","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"SubSequence"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(through:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/count":{"title":"count","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/count","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"count","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/count","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/index(_:offsetBy:)":{"title":"index(_:offsetBy:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/index(_:offsetby:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Index"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offsetBy"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Index","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/index(_:offsetBy:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"title":"Configurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configurations","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","navigatorTitle":[{"kind":"identifier","text":"Configurations"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/underestimatedCount":{"title":"underestimatedCount","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/underestimatedcount","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"underestimatedCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/underestimatedCount","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/suffix(_:)":{"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/suffix(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"suffix"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SubSequence","kind":"typeIdentifier"}],"title":"suffix(_:)","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations\/suffix(_:)","abstract":[],"role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/formIndex(_:offsetBy:)":{"title":"formIndex(_:offsetBy:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/formindex(_:offsetby:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"formIndex","kind":"identifier"},{"kind":"text","text":"("},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Index","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offsetBy"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/formIndex(_:offsetBy:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/dropFirst(_:)":{"title":"dropFirst(_:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/dropfirst(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dropFirst","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"SubSequence"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/dropFirst(_:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/randomElement(using:)":{"title":"randomElement(using:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/randomelement(using:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"randomElement","kind":"identifier"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"text":"using","kind":"externalParam"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"T"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Element","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/randomElement(using:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/trimmingPrefix(while:)":{"title":"trimmingPrefix(while:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/trimmingprefix(while:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trimmingPrefix"},{"text":"(","kind":"text"},{"text":"while","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Element"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rethrows","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SubSequence","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/trimmingPrefix(while:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/drop(while:)":{"title":"drop(while:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/drop(while:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drop","kind":"identifier"},{"kind":"text","text":"("},{"text":"while","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Element"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"rethrows","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"SubSequence"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/drop(while:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/prefix(while:)":{"title":"prefix(while:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/prefix(while:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefix"},{"text":"(","kind":"text"},{"text":"while","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Element"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rethrows","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SubSequence","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(while:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/subscript(_:)":{"title":"subscript(_:)","abstract":[{"text":"Returns the ","type":"text"},{"code":"Configuration","type":"codeVoice"},{"text":" object at that index","type":"text"}],"url":"\/documentation\/sdkconfigurations\/configurations\/subscript(_:)","type":"topic","fragments":[{"kind":"keyword","text":"subscript"},{"text":"(","kind":"text"},{"text":"Index","kind":"typeIdentifier","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Iterator","preciseIdentifier":"s:Sl8IteratorQa"},{"kind":"text","text":"."},{"text":"Element","kind":"typeIdentifier","preciseIdentifier":"s:s16IndexingIteratorV7Elementa"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/subscript(_:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/dropLast(_:)":{"title":"dropLast(_:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/droplast(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropLast"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"text":"SubSequence","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/dropLast(_:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/formIndex(after:)":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/formIndex(after:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"formIndex","kind":"identifier"},{"kind":"text","text":"("},{"text":"after","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"text":"Index","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/sdkconfigurations\/configurations\/formindex(after:)","title":"formIndex(after:)","type":"topic","abstract":[]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/endIndex":{"title":"endIndex","abstract":[{"text":"The array’s “past the end” position—that is, the position one greater than the last valid subscript argument.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"endIndex"}],"url":"\/documentation\/sdkconfigurations\/configurations\/endindex","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"endIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa","text":"Index","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/endIndex","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/map(_:)-u8uh":{"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/map(_:)-u8uh","role":"symbol","kind":"symbol","url":"\/documentation\/sdkconfigurations\/configurations\/map(_:)-u8uh","title":"map(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"map"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"kind":"text","text":">(("},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Element"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"rethrows","kind":"keyword"},{"kind":"text","text":" -> ["},{"text":"T","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/makeIterator()":{"title":"makeIterator()","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/makeiterator()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeIterator","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"IndexingIterator","kind":"typeIdentifier","preciseIdentifier":"s:s16IndexingIteratorV"},{"kind":"text","text":"<"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":">"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/makeIterator()","role":"symbol","conformance":{"constraints":[{"code":"Iterator","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"IndexingIterator<Self>","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]}},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/index(_:offsetBy:limitedBy:)":{"title":"index(_:offsetBy:limitedBy:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/index(_:offsetby:limitedby:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"text":"Index","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"offsetBy","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"limitedBy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Index"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"text":"Index","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/index(_:offsetBy:limitedBy:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/first":{"title":"first","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/first","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"first"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Element","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/first","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/Index":{"title":"Configurations.Index","abstract":[],"navigatorTitle":[{"text":"Index","kind":"identifier"}],"url":"\/documentation\/sdkconfigurations\/configurations\/index","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Index"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Index","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/firstIndex(where:)":{"title":"firstIndex(where:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstIndex","kind":"identifier"},{"kind":"text","text":"("},{"text":"where","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Element"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") ","kind":"text"},{"text":"rethrows","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"text":"Index","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/firstIndex(where:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations\/firstindex(where:)"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/formIndex(_:offsetBy:limitedBy:)":{"title":"formIndex(_:offsetBy:limitedBy:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/formindex(_:offsetby:limitedby:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"formIndex","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Index","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"offsetBy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"limitedBy"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Index","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/formIndex(_:offsetBy:limitedBy:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/suffix(from:)":{"title":"suffix(from:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/suffix(from:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"suffix","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Index"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"text":"SubSequence","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/suffix(from:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/prefix(upTo:)":{"title":"prefix(upTo:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/prefix(upto:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefix"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"upTo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"text":"Index","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SubSequence","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(upTo:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/split(maxSplits:omittingEmptySubsequences:whereSeparator:)":{"title":"split(maxSplits:omittingEmptySubsequences:whereSeparator:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/split(maxsplits:omittingemptysubsequences:whereseparator:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"split","kind":"identifier"},{"kind":"text","text":"("},{"text":"maxSplits","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"omittingEmptySubsequences"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"whereSeparator","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Element"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"text":"rethrows","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SubSequence","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/split(maxSplits:omittingEmptySubsequences:whereSeparator:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/randomElement()":{"title":"randomElement()","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/randomelement()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"randomElement","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Element"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/randomElement()","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/prefix(_:)":{"title":"prefix(_:)","abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations\/prefix(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prefix","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SubSequence","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(_:)","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"type":"topic","kind":"symbol","title":"SDKConfigurations","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","url":"\/documentation\/sdkconfigurations","role":"collection","abstract":[]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/index(after:)":{"title":"index(after:)","abstract":[{"type":"text","text":"Returns the position immediately after the given index."}],"url":"\/documentation\/sdkconfigurations\/configurations\/index(after:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"},{"text":"(","kind":"text"},{"text":"after","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa","kind":"typeIdentifier","text":"Index"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa","text":"Index","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/index(after:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/count","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/endIndex","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/first","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/indices","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/isEmpty","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/startIndex","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/underestimatedCount"]},{"generated":true,"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/distance(from:to:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/drop(while:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/dropFirst(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/dropLast(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/firstIndex(where:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/formIndex(_:offsetBy:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/formIndex(_:offsetBy:limitedBy:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/formIndex(after:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/index(_:offsetBy:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/index(_:offsetBy:limitedBy:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/index(after:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/makeIterator()","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/map(_:)-u8uh","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(through:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(upTo:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/prefix(while:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/randomElement()","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/randomElement(using:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/split(maxSplits:omittingEmptySubsequences:whereSeparator:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/suffix(_:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/suffix(from:)","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/trimmingPrefix(while:)"],"title":"Instance Methods"},{"title":"Subscripts","identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/subscript(_:)"],"generated":true},{"identifiers":["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Index"],"generated":true,"title":"Type Aliases"}],"path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"startIndex","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1startIndex\/title"},{"value":[{"text":"startIndex","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1startIndex\/fragments","op":"replace"},{"value":"ZDKConfigurations","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments","op":"replace","value":[{"text":"ZDKConfigurations","kind":"identifier"}]},{"value":"endIndex","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1endIndex\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1endIndex\/fragments","value":[{"text":"endIndex","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}