{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConfigArrayType","kind":"identifier"},{"text":" = [","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration","kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]"}]}]}],"metadata":{"title":"Configurations.ConfigArrayType","roleHeading":"Type Alias","navigatorTitle":[{"text":"ConfigArrayType","kind":"identifier"}],"externalID":"s:17SDKConfigurations14ConfigurationsC15ConfigArrayTypea","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConfigArrayType","kind":"identifier"}],"modules":[{"name":"SDKConfigurations"}],"role":"symbol","symbolKind":"typealias"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/ConfigArrayType"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdkconfigurations\/configurations\/configarraytype"]}],"kind":"symbol","references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configuration":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"Configuration","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration","url":"\/documentation\/sdkconfigurations\/configuration","role":"symbol","abstract":[]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/ConfigArrayType":{"kind":"symbol","title":"Configurations.ConfigArrayType","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConfigArrayType"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/ConfigArrayType","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConfigArrayType"}],"type":"topic","url":"\/documentation\/sdkconfigurations\/configurations\/configarraytype"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"title":"Configurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configurations","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","navigatorTitle":[{"kind":"identifier","text":"Configurations"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"type":"topic","kind":"symbol","title":"SDKConfigurations","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","url":"\/documentation\/sdkconfigurations","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKConfiguration","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/fragments","value":[{"kind":"identifier","text":"ZDKConfiguration"}]},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title","value":"ZDKConfigurations","op":"replace"},{"op":"replace","value":[{"text":"ZDKConfigurations","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments"}]}]}