{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"configs","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/ConfigArrayType","kind":"typeIdentifier","text":"ConfigArrayType","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC15ConfigArrayTypea"},{"kind":"text","text":" { get }"}],"languages":["swift"]}]}],"metadata":{"title":"configs","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"configs"}],"externalID":"c:@M@SDKConfigurations@objc(cs)ZDKConfigurations(py)configs","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"configs","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConfigArrayType","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC15ConfigArrayTypea","kind":"typeIdentifier"}],"modules":[{"name":"SDKConfigurations"}],"role":"symbol","symbolKind":"property"},"identifier":{"url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/configs","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations"]]},"variants":[{"paths":["\/documentation\/sdkconfigurations\/configurations\/configs"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdkconfigurations\/configurations\/configs"]}],"kind":"symbol","references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"title":"Configurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configurations","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","navigatorTitle":[{"kind":"identifier","text":"Configurations"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/configs":{"title":"configs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configs"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"configs","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConfigArrayType","kind":"typeIdentifier","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC15ConfigArrayTypea"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/configs","url":"\/documentation\/sdkconfigurations\/configurations\/configs","role":"symbol","kind":"symbol","abstract":[]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"type":"topic","kind":"symbol","title":"SDKConfigurations","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","url":"\/documentation\/sdkconfigurations","role":"collection","abstract":[]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/ConfigArrayType":{"kind":"symbol","title":"Configurations.ConfigArrayType","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConfigArrayType"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/ConfigArrayType","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConfigArrayType"}],"type":"topic","url":"\/documentation\/sdkconfigurations\/configurations\/configarraytype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"configs","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"configs","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<ZDKConfiguration>>"},{"text":" * ","kind":"text"},{"text":"configs","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title","value":"ZDKConfigurations"},{"value":[{"text":"ZDKConfigurations","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments"},{"op":"replace","value":"configs","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1configs\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1configs\/fragments","value":[{"text":"configs","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}