{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endIndex","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Index","kind":"typeIdentifier","text":"Index","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"abstract":[{"text":"The array’s “past the end” position—that is, the position one greater than the last valid subscript argument.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdkconfigurations\/configurations\/endindex"]},{"paths":["\/documentation\/sdkconfigurations\/configurations\/endindex"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Collection-Implementations"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/endIndex","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"endIndex"}],"role":"symbol","roleHeading":"Instance Property","extendedModule":"SDKConfigurations","title":"endIndex","symbolKind":"property","modules":[{"name":"SDKConfigurations"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"endIndex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Index","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa"}],"externalID":"c:@CM@SDKConfigurations@objc(cs)ZDKConfigurations(py)endIndex"},"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/Index":{"title":"Configurations.Index","abstract":[],"navigatorTitle":[{"text":"Index","kind":"identifier"}],"url":"\/documentation\/sdkconfigurations\/configurations\/index","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Index"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Index","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"title":"Configurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configurations","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","navigatorTitle":[{"kind":"identifier","text":"Configurations"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"type":"topic","kind":"symbol","title":"SDKConfigurations","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","url":"\/documentation\/sdkconfigurations","role":"collection","abstract":[]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/endIndex":{"title":"endIndex","abstract":[{"text":"The array’s “past the end” position—that is, the position one greater than the last valid subscript argument.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"endIndex"}],"url":"\/documentation\/sdkconfigurations\/configurations\/endindex","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"endIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa","text":"Index","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/endIndex","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/Collection-Implementations":{"title":"Collection Implementations","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Collection-Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations\/collection-implementations"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"endIndex"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"endIndex"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"endIndex","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title","value":"ZDKConfigurations","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments","value":[{"kind":"identifier","text":"ZDKConfigurations"}]},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1endIndex\/title","value":"endIndex","op":"replace"},{"value":[{"text":"endIndex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1endIndex\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}