{"abstract":[{"type":"text","text":"The position of the first element in a nonempty array."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/startIndex"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Index","text":"Index"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Collection-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdkconfigurations\/configurations\/startindex"]},{"paths":["\/documentation\/sdkconfigurations\/configurations\/startindex"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SDKConfigurations"}],"roleHeading":"Instance Property","symbolKind":"property","title":"startIndex","externalID":"c:@CM@SDKConfigurations@objc(cs)ZDKConfigurations(py)startIndex","navigatorTitle":[{"text":"startIndex","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"startIndex","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa","text":"Index"}]},"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"type":"topic","kind":"symbol","title":"SDKConfigurations","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","url":"\/documentation\/sdkconfigurations","role":"collection","abstract":[]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"title":"Configurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configurations","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","navigatorTitle":[{"kind":"identifier","text":"Configurations"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/startIndex":{"title":"startIndex","url":"\/documentation\/sdkconfigurations\/configurations\/startindex","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/startIndex","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"startIndex","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Index","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC5Indexa"}],"navigatorTitle":[{"kind":"identifier","text":"startIndex"}],"abstract":[{"text":"The position of the first element in a nonempty array.","type":"text"}]},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/Index":{"title":"Configurations.Index","abstract":[],"navigatorTitle":[{"text":"Index","kind":"identifier"}],"url":"\/documentation\/sdkconfigurations\/configurations\/index","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Index"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Index","role":"symbol"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/Collection-Implementations":{"title":"Collection Implementations","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/Collection-Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/sdkconfigurations\/configurations\/collection-implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"startIndex"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"startIndex","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startIndex"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"ZDKConfigurations","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title"},{"value":[{"kind":"identifier","text":"ZDKConfigurations"}],"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments","op":"replace"},{"op":"replace","value":"startIndex","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1startIndex\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1startIndex\/fragments","value":[{"text":"startIndex","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}