{"sections":[],"abstract":[{"type":"text","text":"Initializes a new SDKConfiguration object."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdkconfigurations\/configurations\/init(configs:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdkconfigurations\/configurations\/init(configs:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/init(configs:)"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations"]]},"metadata":{"modules":[{"name":"SDKConfigurations"}],"symbolKind":"init","navigatorTitle":[{"text":"initWithConfigs:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configs","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"text":"])","kind":"text"}],"title":"init(configs:)","roleHeading":"Initializer","externalID":"c:@M@SDKConfigurations@objc(cs)ZDKConfigurations(im)initWithConfigs:","role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","kind":"typeIdentifier","text":"Configuration","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration"},{"kind":"text","text":"])"}],"languages":["swift"]}]},{"parameters":[{"name":"configs","content":[{"type":"paragraph","inlineContent":[{"text":"A array of ","type":"text"},{"type":"codeVoice","code":"Configuration"},{"type":"text","text":" objects."}]}]}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A SDKConfiguration object."}]}],"kind":"content"}],"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"title":"SDKConfigurations","url":"\/documentation\/sdkconfigurations","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","role":"collection"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/init(configs:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConfigs:"}],"title":"init(configs:)","type":"topic","abstract":[{"type":"text","text":"Initializes a new SDKConfiguration object."}],"url":"\/documentation\/sdkconfigurations\/configurations\/init(configs:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configs"},{"kind":"text","text":": ["},{"text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/init(configs:)"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configuration":{"url":"\/documentation\/sdkconfigurations\/configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","title":"Configurations","role":"symbol","navigatorTitle":[{"text":"Configurations","kind":"identifier"}],"abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configurations"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithConfigs:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithConfigs:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfigs:"},{"kind":"text","text":"("},{"text":"NSArray<id<ZDKConfiguration>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"configs","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1init(configs:)\/title","value":"initWithConfigs:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfigs:"}],"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations~1init(configs:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/title","op":"replace","value":"ZDKConfiguration"},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/fragments","value":[{"kind":"identifier","text":"ZDKConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title","op":"replace","value":"ZDKConfigurations"},{"value":[{"kind":"identifier","text":"ZDKConfigurations"}],"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments","op":"replace"}]}]}