{"identifier":{"url":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/subscript(forType:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"subscript"},{"kind":"text","text":"<"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"forType","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"T","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC7forTypexSgxm_tcAA13ConfigurationRzluip1TL_xmfp","kind":"typeIdentifier"},{"text":".Type) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC7forTypexSgxm_tcAA13ConfigurationRzluip1TL_xmfp","text":"T"},{"text":"? ","kind":"text"},{"text":"where","kind":"keyword"},{"kind":"text","text":" "},{"text":"T","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A type that conforms to "},{"code":"Configuration","type":"codeVoice"}]}],"name":"index"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The first uiConfig of type "},{"type":"codeVoice","code":"T"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/sdkconfigurations\/configurations\/subscript(fortype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"abstract":[{"text":"Returns the first ","type":"text"},{"code":"Configuration","type":"codeVoice"},{"type":"text","text":" object that is of "},{"type":"codeVoice","code":"T"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations"]]},"metadata":{"title":"subscript(forType:)","externalID":"s:17SDKConfigurations14ConfigurationsC7forTypexSgxm_tcAA13ConfigurationRzluip","modules":[{"name":"SDKConfigurations"}],"symbolKind":"subscript","extendedModule":"SDKConfigurations","fragments":[{"text":"subscript","kind":"keyword"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"forType","kind":"externalParam"},{"kind":"text","text":" _: "},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC7forTypexSgxm_tcAA13ConfigurationRzluip1TL_xmfp"},{"text":".Type) -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC7forTypexSgxm_tcAA13ConfigurationRzluip1TL_xmfp"},{"text":"?","kind":"text"}],"roleHeading":"Instance Subscript","role":"symbol"},"references":{"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations","title":"Configurations","role":"symbol","navigatorTitle":[{"text":"Configurations","kind":"identifier"}],"abstract":[],"url":"\/documentation\/sdkconfigurations\/configurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configurations"}],"type":"topic"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configurations/subscript(forType:)":{"kind":"symbol","title":"subscript(forType:)","type":"topic","abstract":[{"type":"text","text":"Returns the first "},{"code":"Configuration","type":"codeVoice"},{"text":" object that is of ","type":"text"},{"type":"codeVoice","code":"T"}],"url":"\/documentation\/sdkconfigurations\/configurations\/subscript(fortype:)","role":"symbol","fragments":[{"kind":"keyword","text":"subscript"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"T"},{"text":">(","kind":"text"},{"text":"forType","kind":"externalParam"},{"kind":"text","text":" _: "},{"kind":"typeIdentifier","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC7forTypexSgxm_tcAA13ConfigurationRzluip1TL_xmfp","text":"T"},{"kind":"text","text":".Type) -> "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:17SDKConfigurations14ConfigurationsC7forTypexSgxm_tcAA13ConfigurationRzluip1TL_xmfp"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configurations\/subscript(forType:)"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations":{"title":"SDKConfigurations","url":"\/documentation\/sdkconfigurations","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations","role":"collection"},"doc://com.zendesk.SDKConfigurations/documentation/SDKConfigurations/Configuration":{"url":"\/documentation\/sdkconfigurations\/configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.zendesk.SDKConfigurations\/documentation\/SDKConfigurations\/Configuration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/title","op":"replace","value":"ZDKConfigurations"},{"op":"replace","value":[{"text":"ZDKConfigurations","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configurations\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/title","value":"ZDKConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SDKConfigurations~1documentation~1SDKConfigurations~1Configuration\/fragments","value":[{"kind":"identifier","text":"ZDKConfiguration"}]}]}]}